//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverestORM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlTemlates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlTemlates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverestORM.SqlTemlates", typeof(SqlTemlates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///  RF.RDB$FIELD_NAME FIELD_NAME,
        ///  CASE F.RDB$FIELD_TYPE
        ///    WHEN 7 THEN
        ///      CASE F.RDB$FIELD_SUB_TYPE
        ///        WHEN 0 THEN &apos;SMALLINT&apos;
        ///        WHEN 1 THEN &apos;NUMERIC(&apos; || F.RDB$FIELD_PRECISION || &apos;, &apos; || (-F.RDB$FIELD_SCALE) || &apos;)&apos;
        ///        WHEN 2 THEN &apos;DECIMAL&apos;
        ///      END
        ///    WHEN 8 THEN
        ///      CASE F.RDB$FIELD_SUB_TYPE
        ///        WHEN 0 THEN &apos;INTEGER&apos;
        ///        WHEN 1 THEN &apos;NUMERIC(&apos;  || F.RDB$FIELD_PRECISION || &apos;, &apos; || (-F.RDB$FIELD_SCALE) || &apos;)&apos;
        ///        WHEN 2 THEN &apos;DECIMAL&apos;
        ///      END
        ///    WH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ColumnsQuery {
            get {
                return ResourceManager.GetString("ColumnsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM {0} WHERE {1} = @{1}.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to execute block ({0})
        ///as 
        ///begin 
        ///{1} end.
        /// </summary>
        internal static string ExecuteBlock {
            get {
                return ResourceManager.GetString("ExecuteBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO {0} ({1}) VALUES ({2});.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO {0} ({1}) VALUES ({2}) RETURNING {3}.
        /// </summary>
        internal static string InsertRet {
            get {
                return ResourceManager.GetString("InsertRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT {0} FROM {1} WHERE {2}.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE {0} SET {2} WHERE {1} = @{1}.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a{0} TYPE OF COLUMN &quot;&quot;{1}&quot;&quot;.&quot;&quot;{2}&quot;&quot; = @a{0}.
        /// </summary>
        internal static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
    }
}
